name: Print Message

on:
  push:
    branches:
      - master
      - dev

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print fixed message
      run: echo "eymen vural harun"

    - name: Print content of text.txt
      run: cat text.txt
