name: Print Message on Push

on:
  push:
    paths:
      - text.txt

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print message
      run: echo "eymen vural"

