name: Bandit Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: bandit -r .
